services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"

  admin_ui:
    build:
      context: ./services/admin_ui
    restart: unless-stopped
    depends_on:
      - orders_api
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000

  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - "8080:8080"

  orders_api:
    build:
      context: ./services/orders_api
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"

volumes:
  db_data:
